In [39]:
import numpy
import math
import pandas
import scipy.optimize

In [19]:
datatest=pandas.Series(data=[6.09,6.08,6.1,6.1,6.09,6.11],index=[2000,2002,2004,2006,2008,2010])

In [21]:
yeardata=datatest.index
popdata=datatest.values
popdata

array([ 6.09,  6.08,  6.1 ,  6.1 ,  6.09,  6.11])

In [50]:
def model_lin_equation():
    #returns a series containing the best fit linear model of population as values and the index as time
    def fitFunc(year,m,b):
        return m*year+b
    best_params, error_array=scipy.optimize.curve_fit(fitFunc,yeardata,popdata)
    #scipy.curv_fit outputs the optimized parameters defined in the function fitFunc and an array of standard deviations from the data values.
    for i in range(len(yeardata)):
        year=yeardata[i]
        popmodel[i]=fitFunc(year, bestparams[0],bestparams[1])
        #array of population values according to best fin model gets linear fit function with the best fit parameters for a and b, stored in bestparams[]
        model[i]=yeardata[i],popmodel[i]
    return model
model_lin_equation()

NameError: name 'bestparams' is not defined

In [30]:
def model_lin_error():
    #returns a series containing the best fit linear model of population as values and the index as time
    def fitFunc(year,m,b):
        return m*year+b
    best_params, error_array=scipy.optimize.curve_fit(fitFunc,yeardata,popdata)
    total_error=0
    for i in range(len(error_array)):
        total_error+=error_array[i]
    return total_error

array([ -2.20851537e-03,   4.42808614e+00])

In [49]:
def model_quad_equation():
    #returns an equation in form pop=ax^2+bx+c and an array of standard deviations
    def fitFunc(year,a,b,c):
         return a*(year**2)+b*year+c
    (best_params, error_array)=scipy.optimize.curve_fit(fitFunc,yeardata,popdata)    
    for i in range(len(yeardata)):
        year=yeardata[i]
        popmodel[i]=fitFunc(year, bestparams[0],bestparams[1], bestparams[2])
        model[i]=yeardata[i],popmodel[i]
    return (model)
model_quad_equation()

NameError: name 'bestparams' is not defined

In [33]:
def model_quad_error():
    #returns an equation in form pop=ax^2+bx+c and an array of standard deviations
    def fitFunc(year,a,b,c):
         return a*(year**2)+b*year+c
    best_params, error_array=scipy.optimize.curve_fit(fitFunc,yeardata,popdata)    
    total_error=0
    for i in range(len(error_array)):
        total_error+=error_array[i]
    return total_error
model_quad_error()

array([  6.72026675e-01,  -2.69483728e+03,   2.70157684e+06])

In [47]:
def model_poly_equation():
    def fitFunc(x,a,b,c,d,e,f):
        return a*(x**5)+b*(x**4)+c*(x**3)+d*(x**2)+e*x+f
    best_params, error_array=scipy.optimize.curve_fit(fitFunc,yeardata,popdata)    
    for i in range(len(yeardata)):
        year=yeardata[i]
        popmodel[i]=fitFunc(year, bestparams[0],bestparams[1], bestparams[2], bestparams[3], bestparams[4], bestparams[5])
        model[i]=yeardata[i],popmodel[i]
    return (model)
model_poly_equation()

C:\Users\manthony\AppData\Local\Continuum\Anaconda3\lib\site-packages\scipy\optimize\minpack.py:779: OptimizeWarning: Covariance of the parameters could not be estimated
  category=OptimizeWarning)


NameError: name 'bestparams' is not defined

In [44]:
def model_poly_error():
    def fitFunc(x,a,b,c,d,e,f):
        return a*(x**5)+b*(x**4)+c*(x**3)+d*(x**2)+e*x+f
    best_params, error_array=scipy.optimize.curve_fit(fitFunc,yeardata,popdata)    
    total_error=0
    for i in range(len(error_array)):
        total_error+=error_array[i]
    return total_error
model_poly_error()

C:\Users\manthony\AppData\Local\Continuum\Anaconda3\lib\site-packages\scipy\optimize\minpack.py:779: OptimizeWarning: Covariance of the parameters could not be estimated
  category=OptimizeWarning)


array([ inf,  inf,  inf,  inf,  inf,  inf])

In [46]:
def model_log_equation():
    def fitFunc(x,a,b,c,d):
        return a*math.log(b*x+c)+d
    best_params, error_array=scipy.optimize.curve_fit(fitFunc,yeardata,popdata)    
    total_error=0
    for i in range(len(yeardata)):
        year=yeardata[i]
        popmodel[i]=fitFunc(year, bestparams[0],bestparams[1], bestparams[2], bestparams[3])
        model[i]=yeardata[i],popmodel[i]
    return (model)
model_log_equation()

TypeError: must be real number, not Float64Index

In [43]:
def model_log_error():
    #returns a series containing the best fit logarithmic model of population as values and the index as time
    def fitFunc(x,a,b,c,d):
        return a*math.log(bx+c)+d
    best_params, error_array=scipy.optimize.curve_fit(fitFunc,yeardata,popdata)    
    total_error=0
    for i in range(len(error_array)):
        total_error+=error_array[i]
    return total_error
model_log_error()

TypeError: must be real number, not Int64Index

In [31]:
def choose_model():
    log=model_log_error(yeardata,popdata)
    poly=model_poly_error(yeardata,popdata)
    lin=model_lin_error(yeardata,popdata)
    quad=model_quad_error(yeardata,popdata)
    best=min(log,poly,lin,quad)
    if best==log:
        return model_log_equation(yeardata,popdata)
    if best==poly:
        return model_poly_equation(yeardata,popdata)
    if best==lin:
        return model_lin_equation(yeardata,popdata)
    if best==quad:
        return model_quad_equation(yeardata,popdata)
